"""
This type stub file was generated by pyright.
"""

from .rel import (EV_PERSIST, EV_READ, EV_SIGNAL, EV_TIMEOUT, EV_WRITE, abort,
                  abort_branch, dispatch, event, init, initialize, is_running,
                  loop, override, read, report, safe_read, set_sleep,
                  set_turbo, signal, supported_methods, sys, thread, tick,
                  timeout, write)
from .version import __version__
