"""
This type stub file was generated by pyright.
"""

import unittest

"""
REL Test Suite - regular unittest compatible suite
Submitted by Chris Clark on 10/12/2011. Thanks, Chris!

Original code here:
http://code.google.com/r/clach04-pyeventtestfixes/source/browse/test.py

Sample usage:

    rel\test.py
    rel\test.py -v
    rel\test.py -v EventTest.test_exception EventTest.test_timeout
    ... etc.
"""
unittest2 = ...
possible_build_dir = ...
if possible_build_dir:
    ...
class EventTest(unittest.TestCase):
    def skip(self, reason): # -> None:
        """Skip current test because of `reason`.
       
        NOTE currently expects unittest2, and defaults to "pass"
        if not available.
       
        unittest2 does NOT work under Python 2.2.
        Could potentially use nose or py.test which has (previously)
        supported Python 2.2
          * nose
            http://python-nose.googlecode.com/svn/wiki/NoseWithPython2_2.wiki
          * py.test
            http://codespeak.net/pipermail/py-dev/2005-February/000203.html
        """
        ...
    
    def setUp(self): # -> None:
        ...
    
    def test_timeout(self): # -> None:
        ...
    
    def test_timeout2(self): # -> None:
        ...
    
    def test_signal(self): # -> None:
        ...
    
    def test_signal2(self): # -> None:
        ...
    
    def test_read(self): # -> None:
        ...
    
    def test_read2(self): # -> None:
        ...
    
    def test_exception(self): # -> None:
        ...
    
    def test_abort(self): # -> None:
        ...
    
    def test_callback_exception(self): # -> None:
        ...
    
    def test_thread(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
